name: multijobs_needs

on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-24.04
    name: multi steps
    steps:
      - run: echo "A job consists of"
      - run: echo "one or more steps"
      - run: echo "which run sequentially"
      - run: echo "within the same compute environment"
  job-2:
    runs-on: ubuntu-24.04
    name: multi jobs running in parallel
    steps:
      - run: echo "Multiple jobs can run in parallel"
  job-3:
    runs-on: ubuntu-24.04
    name: needs_command 
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "They can also depend on one another..."
  job-4:
    runs-on: ubuntu-24.04
    name: needs_command 
    needs:
      - job-2
      - job-3
    steps:
      - run: echo "...to form a directed acyclic graph (DAG)"
      #It allows you to control job order and build a Directed Acyclic Graph (DAG) — a fancy term for a dependency chain where jobs flow in one direction (no loops).