name: Step Types

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    name: run on bash terminal
    steps:
      - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"

  say-hello-inline-python:
    runs-on: ubuntu-24.04
    name: run on python terminal
    steps:
      - run: print("Hello from an inline python script in a GitHub Action Workflow!")
        shell: python

  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
      - name: say hello world
        uses: actions/hello-world-javascript-action@v1 
        with:
          who-to-greet: "from an action in the GitHub Action marketplace! 👋"